sudo: false
language: php
php:
  - 5.6
  - 5.5
  - 5.4

matrix:
  allow_failures:
    - php: nightly

before_install:
  - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar

script:
  - composer validate
  - composer install
  - mysql -e "CREATE DATABASE wordpress_tests;" -uroot
  - cp .env.travis .env
  - php wp-cli.phar core install --path=web/wp --url=example.com --title=WP --admin_user=test --admin_password=test --admin_email=user@example.com
  - php web/index.php
