sudo: false
language: php
php:
- 7.0
- 5.6
addons:
  hosts:
  - travis.dev
before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
script:
- composer validate
- composer install
- ./tests/bin/setup.sh
- ./vendor/bin/codecept run
notifications:
  slack:
    secure: RDOtCNSwSeTnJZL1PkcGgma6ZKtsdy0mDWD8DYyt2tZxqlWcEQRY6LkLmX4VjaJKrbj2ZGts2tmMmK15NMsTfQW5dbzt1lKXhIIUDG0z9FcH74ZskqtMVCiKxItEooX2itMRFZP+eFZu9OYZksg6nPCOaoRHa98IOCcPsgx3MX4=
